### PR TITLE
Andy/fix/not used vars hp

### PR DESCRIPTION
**Pull request by AndrewCerveny**
# Description

All of the recipe cards were not tabAble and now they are. Also got rid of extra variables for the homePage. 
Also added requirements for the pantry form HTML input areas. 

Fixes # (issue)

## Type of change
- [x] HTML
- [ ] CSS
- [x] DOM
- [ ] DataModel
- [ ] API
- [x] ScriptsJS

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
1. pantry area hoover in text book and a warning appears below
2. you can press the tab button and go image to image 

- [x] Test Approved
Screen Shot 2022-11-03 at 9 18 14 PM
added tabindex. 

Screen Shot 2022-11-05 at 2 29 39 PM
added required and specified text

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by Courtney-Lippman** [comment]
Hey Andy! The tabbing looks great! I noticed the delete icon is not tabable which might be a problem when a user wants to delete a recipe from the saved recipe page.

**Comment by AndrewCerveny** [comment]
I see what you mean i'll look into trying to add another tab index and see if I can get that desired response.

**Comment by AndrewCerveny** [comment]
updated the branch 
Screen Shot 2022-11-05 at 8 08 07 PM

above show that in the middle of the function within the trash can <p tag> I've added and tabIndex ='0'

Screen Shot 2022-11-05 at 8 05 16 PM

Above shows that the trashCans are getting a highlighted region

**Comment by AndrewCerveny** [comment]
Updated Accessibility in a group setting! Everything is tab friendly using the enter key on access

**Review by daniabee — APPROVED** [review]

**Pull request merged**
